### PR TITLE
[WIP] 1.x refactor

### PR DESCRIPTION
**Pull request by jlengstorf**
**NOTE:** This PR can be installed using:

```
yarn add @gramps/cli@beta
```

### Status of this PR

- [x] Implement new API per #9 
- [x] Start a default GraphQL gateway with no data sources by default (e.g. `gramps dev`)
- [x] Load one or more data sources for local development when the `-d` option is present (#11)
- [x] Use a custom gateway if one is provided (e.g. `gramps dev -g ./myserver.js`) (#10)
- [x] Disable Babel transpilation if the `--no-transpile` flag is set
- [x] Enable mock data if the `--mock` flag is set

### CODE REVIEW

**Comment by jlengstorf** [comment]
@ecwyne The CLI should be ready to go. I ran it through some paces:

- set up a custom gateway with the XKCD data source (see [this gist](https://gist.github.com/jlengstorf/9dd909f8240b91ef2e55aa232c66eb95) for a working implementation)
- ran the default gateway with no data sources
- ran the default gateway with 1 and 2 data sources
- ran the default gateway with a bogus data source path to ensure it warned and skipped it
- ran a custom gateway
- ran a custom gateway with a data source
- ran a custom gateway with a local data source that overrides the gateway's installed data source

If you have a few minutes to bang on this with a hammer and see if I missed anything, I'd appreciate it. Everything's on npm under the `@beta` tag — see the [package.json of that quickstart gist](https://gist.github.com/jlengstorf/9dd909f8240b91ef2e55aa232c66eb95) for the latest versions.

Thanks!

**Comment by ecwyne** [comment]
I'll take a look today and let you know my findings. 🎆

**Comment by ecwyne** [comment]
@jlengstorf 
I've had a lot of success with my testing. Apart from needing to [update the `dev` script](https://github.com/gramps-graphql/data-source-xkcd/pull/1/commits/c980b465c2612d9d76699c4a7edfeba9dbe14392) on `@gramps/data-source-xkcd` I haven't run into any issues yet.

The only thing that seems off to me at this point is that is logs `-> cleaning up temporary files` even when there weren't any temporary files made. Eg. when I run `gramps --version` there is no reason to remove temporary files

**Comment by ecwyne** [comment]
I also just noticed that when I remove all versions of `@gramps/cli` and do a fresh global install using `yarn global add @gramps/cli@beta` and then try to run `gramps --version` I get 

```
Error: Cannot find module '@gramps/gramps'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/ewyne/.config/yarn/global/node_modules/@gramps/cli/lib/gateway.js:1:324)
    at Module._compile (module.js:624:30)
    at Object.extWrap (/Users/ewyne/.config/yarn/global/node_modules/reify/node/compile-hook.js:59:7)
    at Object.extManager (/Users/ewyne/.config/yarn/global/node_modules/reify/node/compile-hook.js:19:12)
    at Object.manager [as .js] (/Users/ewyne/.config/yarn/global/node_modules/reify/node/wrapper.js:108:20)
    at Module.load (module.js:545:32)
```
I thinks this is an issue with having `@gramps/gramps` as *both* a [peerDependency and devDependency](https://github.com/gramps-graphql/gramps-cli/blob/1e9b9b16cb985b114c67b06c798f3930d19db9a0/package.json#L50-L54)

**Comment by jlengstorf** [comment]
Hmm... what's the best practice for this? We can potentially just include `@gramps/gramps` as a dependency since technically it's required for normal operation. Do you see that causing problems?

**Comment by jlengstorf** [comment]
Something I'd love to make possible is executing via `npx` for really easy testing:

```
npx @gramps/cli dev
```

I tried that and got the same error about `@gramps/gramps` being absent. 😕

**Comment by ecwyne** [comment]
Interesting, it looks like `@babel/cli` [has both peer/devDependencies for `@babel/core`](https://github.com/babel/babel/blob/master/packages/babel-cli/package.json#L32-L35)

Looking into this further.

**Comment by ecwyne** [comment]
I **think** that `@gramps/gramps` maybe *should* be a true `dependency`?
The only issue I foresee is that I believe it should also be a true `dependency` of the gateway

**Comment by jlengstorf** [comment]
You know what — I think we can just include it. It's only used in `lib/gateway.js` for the default gateway, so it shouldn't be possible for there to be a version clash. When a gateway is being used, the default gateway (and therefore `@gramps/gramps`) will never be loaded.

I'll make the adjustments and push.

**Comment by jlengstorf** [comment]
@ecwyne I moved GrAMPS core to a dependency, fixed the cleanup to only fire if a temp dir exists, and fixed a bug I found where the CLI couldn't delete temp files if it was run from outside its root directory.

What do you think — should we call this 1.0.0? 😄

**Comment by ecwyne** [comment]
🚀

**Comment by jlengstorf** [comment]
💥

**Pull request merged**
